#baseURL = "https://glinders.github.io/"
#languageCode = "en-us"
#title = "My Hugo Site"
#theme = "hello-friend-ng"

baseurl = "/"
languageCode = "en-us"
theme = "hello-friend-ng"

[pagination]
  pagerSize=5

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "post"
  # "light" or "dark"
  defaultTheme = "dark"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 2
  # Enable to show reading time in minutes for posts
  showReadingTime = false
  # site wide date format, see $.Site.Params.DateFormatSingle and ...List
  dateFormatSingle = "DFff: 01 Jan 2006"
  dateFormatList = "DFgg: 01 Jan 2006"



[languages]
  [languages.en]
    title = "Hello Friend"
    subtitle = "A simple theme for Hugo"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    writtenBy = "Written by"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    minuteReadingTime = "min read"
    dateFormatSingle = "DFhh: 01 Jan 2006"
    dateFormatList = "DFii: 01 Jan 2006"
    DateFormatSingle = "DFjj: 01 Jan 2006"
    DateFormatList = "DFkk: 01 Jan 2006"

    [languages.en.params.logo]
      logoText = "hello friend"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "showcase"
        name = "Showcase"
        url = "/showcase"

